version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taxi_api
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: TaxiDatabase
      JWT_SECRET: secret
    restart: unless-stopped

  db:
    container_name: taxi_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TaxiDatabase
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    command:
      - --default-authentication-plugin=mysql_native_password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taxi_frontend
    ports:
      - "80:80"
    depends_on:
      - api
      - db
    restart: unless-stopped

volumes:
  mysql_data: